services:
  mongo:
    image: mongo:latest
    container_name: mongoMonopatin
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
    driver: local